version: "3"
services:
  client:
    image: dungeon-autogen-client
    build: ./client
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=443
    volumes:
      - ./:/home/node/app
    expose:
      - "443"
    ports:
      - "443:443"
    command: >
      bash -c "cd client/build && serve -s -l 443"
