version: "3"
services:
  client:
    image: dungeon-autogen-client
    build: ./client
    user: "node"
    working_dir: /home/node/app
    environment:
      - PORT=3000
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: >
      bash -c "cd client/build && serve -s -l 3000"
